spring.application.name=maps
spring.threads.virtual.enabled=true
server.forward-headers-strategy=framework

management.server.port=8081

# Aktiverar versionering av resurser
spring.web.resources.chain.strategy.content.enabled=true
#spring.web.resources.chain.strategy.content.paths=/**

# Specifikt för WebJars: Gör så att versionen faktiskt syns i URL:en utåt
#spring.web.resources.chain.strategy.fixed.enabled=true
#spring.web.resources.chain.strategy.fixed.paths=/webjars/**
#spring.web.resources.chain.strategy.fixed.version=v1 # Kan vara vad som helst
