name: Build and Push Docker Image

on:
  push:
    branches:
      - prod
jobs:
  build:
    runs-on:  ubuntu-24.04-arm
    defaults:
      run:
        working-directory: springboot
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: maven

      - name: Build and push
        run: |
          mvn -Pnative spring-boot:build-image \
          -B --no-transfer-progress \
          -Dspring-boot.build-image.imageName="${{ secrets.DOCKER_REGISTRY }}/test/springboot:${GITHUB_SHA::7}" \
          -Ddocker.publishRegistry.username="${{ secrets.DOCKER_REGISTRY_USERNAME }}" \
          -Ddocker.publishRegistry.password="${{ secrets.DOCKER_REGISTRY_PASSWORD }}" \
          -Dspring-boot.build-image.publish=true \
          -Dspring-boot.publishRegistry.url="${{ secrets.DOCKER_REGISTRY }}"
          --file pom.xml

      - name: Capture SHA tag
        run: echo "SHA_TAG=\"${{ env.GITHUB_SHA }}\"" >> $GITHUB_ENV
