name: Build and Push Docker Image

on:
  push:
    branches:
      - prod
jobs:
  build:
    runs-on:  ubuntu-24.04-arm
    defaults:
      run:
        working-directory: springboot
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: maven

#      - name: Docker login
#        run:  echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin "${{ secrets.DOCKER_REGISTRY }}"
      - name: Login to Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build
        run: |
          mvn -Pnative spring-boot:build-image \
          -B --no-transfer-progress \
          -Dspring-boot.build-image.imageName="${{ secrets.DOCKER_REGISTRY }}/giteaadmin/springboot:${GITHUB_SHA::7}" \
          --file pom.xml

      - name: Push image
        run: docker push "${{ secrets.DOCKER_REGISTRY }}/giteaadmin/springboot:${GITHUB_SHA::7}"

      - name: Capture SHA tag
        run: echo "SHA_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Authenticate to Kubernetes
        run: |
          echo "${{ secrets.K8S_CA_CERT }}" | base64 --decode > ca.crt
          
          # Set the cluster info
          kubectl config set-cluster my-cluster --server=${{ secrets.K8S_SERVER }} --certificate-authority=ca.crt --embed-certs=true
          
          # Set the credentials - we'll name the entry 'system2025' to match your SA
          kubectl config set-credentials system2025 --token=${{ secrets.K8S_TOKEN }}
          
          # Link them together in a context
          kubectl config set-context default --cluster=my-cluster --user=system2025 --namespace=system2025
          
          kubectl config use-context default

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/system2025-deployment \
          springboot-container=${{ secrets.DOCKER_REGISTRY }}/giteaadmin/springboot:${{ env.SHA_TAG }} \
          -n system2025
