name: Build and Push Docker Image

on:
  push:
    branches:
      - prod
jobs:
  build:
    runs-on:  ubuntu-24.04-arm
    defaults:
      run:
        working-directory: springboot
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: maven

      - name: Docker login
        run:  echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin "${{ secrets.DOCKER_REGISTRY }}"

      - name: Build
        run: |
          mvn -Pnative spring-boot:build-image \
          -B --no-transfer-progress \
          -Dspring-boot.build-image.imageName="${{ secrets.DOCKER_REGISTRY }}/test/springboot:${GITHUB_SHA::7}" \
          --file pom.xml

      - name: Push image
        run: docker push "${{ secrets.DOCKER_REGISTRY }}/test/springboot:${GITHUB_SHA::7}"

      - name: Print Short SHA
        run: echo "SHA_TAG=${GITHUB_SHA::7}"
